{"name": "test_fill_and_submit_form", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=140.0.7339.208)\nStacktrace:\n\tGetHandleVerifier [0x0xc2c333+65459]\n\tGetHandleVerifier [0x0xc2c374+65524]\n\t(No symbol) [0x0xa4d973]\n\t(No symbol) [0x0xa2c19d]\n\t(No symbol) [0x0xac059e]\n\t(No symbol) [0x0xa6f904]\n\t(No symbol) [0x0xab9bf6]\n\t(No symbol) [0x0xa8b38e]\n\t(No symbol) [0x0xa8c274]\n\tGetHandleVerifier [0x0xeaeda3+2697763]\n\tGetHandleVerifier [0x0xea9ec7+2677575]\n\tGetHandleVerifier [0x0xc54194+228884]\n\tGetHandleVerifier [0x0xc449f8+165496]\n\tGetHandleVerifier [0x0xc4b18d+192013]\n\tGetHandleVerifier [0x0xc347d8+99416]\n\tGetHandleVerifier [0x0xc34972+99826]\n\tGetHandleVerifier [0x0xc1ebea+10346]\n\tBaseThreadInitThunk [0x0x7570fcc9+25]\n\tRtlGetAppContainerNamedObjectPath [0x0x7761809e+286]\n\tRtlGetAppContainerNamedObjectPath [0x0x7761806e+238]", "trace": "tests\\test_form.py:18: in test_fill_and_submit_form\n    form_page.open_form_page()\npages\\form_page.py:12: in open_form_page\n    self.open_url(\"https://practice-automation.com/form-fields/\")\npages\\base_page.py:112: in open_url\n    self.wait_for_page_load()\npages\\base_page.py:42: in wait_for_page_load\n    self.handle_alert(1)\npages\\base_page.py:27: in handle_alert\n    alert = WebDriverWait(self.driver, timeout).until(EC.alert_is_present())\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\selenium\\webdriver\\support\\wait.py:129: in until\n    value = method(self._driver)\n            ^^^^^^^^^^^^^^^^^^^^\n..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:856: in _predicate\n    return driver.switch_to.alert\n           ^^^^^^^^^^^^^^^^^^^^^^\n..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\selenium\\webdriver\\remote\\switch_to.py:55: in alert\n    _ = alert.text\n        ^^^^^^^^^^\n..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\selenium\\webdriver\\common\\alert.py:58: in text\n    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:458: in execute\n    self.error_handler.check_response(response)\n..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:232: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nE   from unknown error: web view not found\nE     (Session info: chrome=140.0.7339.208)\nE   Stacktrace:\nE   \tGetHandleVerifier [0x0xc2c333+65459]\nE   \tGetHandleVerifier [0x0xc2c374+65524]\nE   \t(No symbol) [0x0xa4d973]\nE   \t(No symbol) [0x0xa2c19d]\nE   \t(No symbol) [0x0xac059e]\nE   \t(No symbol) [0x0xa6f904]\nE   \t(No symbol) [0x0xab9bf6]\nE   \t(No symbol) [0x0xa8b38e]\nE   \t(No symbol) [0x0xa8c274]\nE   \tGetHandleVerifier [0x0xeaeda3+2697763]\nE   \tGetHandleVerifier [0x0xea9ec7+2677575]\nE   \tGetHandleVerifier [0x0xc54194+228884]\nE   \tGetHandleVerifier [0x0xc449f8+165496]\nE   \tGetHandleVerifier [0x0xc4b18d+192013]\nE   \tGetHandleVerifier [0x0xc347d8+99416]\nE   \tGetHandleVerifier [0x0xc34972+99826]\nE   \tGetHandleVerifier [0x0xc1ebea+10346]\nE   \tBaseThreadInitThunk [0x0x7570fcc9+25]\nE   \tRtlGetAppContainerNamedObjectPath [0x0x7761809e+286]\nE   \tRtlGetAppContainerNamedObjectPath [0x0x7761806e+238]"}, "steps": [{"name": "Open form page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=140.0.7339.208)\nStacktrace:\n\tGetHandleVerifier [0x0xc2c333+65459]\n\tGetHandleVerifier [0x0xc2c374+65524]\n\t(No symbol) [0x0xa4d973]\n\t(No symbol) [0x0xa2c19d]\n\t(No symbol) [0x0xac059e]\n\t(No symbol) [0x0xa6f904]\n\t(No symbol) [0x0xab9bf6]\n\t(No symbol) [0x0xa8b38e]\n\t(No symbol) [0x0xa8c274]\n\tGetHandleVerifier [0x0xeaeda3+2697763]\n\tGetHandleVerifier [0x0xea9ec7+2677575]\n\tGetHandleVerifier [0x0xc54194+228884]\n\tGetHandleVerifier [0x0xc449f8+165496]\n\tGetHandleVerifier [0x0xc4b18d+192013]\n\tGetHandleVerifier [0x0xc347d8+99416]\n\tGetHandleVerifier [0x0xc34972+99826]\n\tGetHandleVerifier [0x0xc1ebea+10346]\n\tBaseThreadInitThunk [0x0x7570fcc9+25]\n\tRtlGetAppContainerNamedObjectPath [0x0x7761809e+286]\n\tRtlGetAppContainerNamedObjectPath [0x0x7761806e+238]\n\n", "trace": "  File \"C:\\Users\\Fr0z3n556\\Desktop\\automation_project\\tests\\test_form.py\", line 18, in test_fill_and_submit_form\n    form_page.open_form_page()\n  File \"C:\\Users\\Fr0z3n556\\Desktop\\automation_project\\pages\\form_page.py\", line 12, in open_form_page\n    self.open_url(\"https://practice-automation.com/form-fields/\")\n  File \"C:\\Users\\Fr0z3n556\\Desktop\\automation_project\\pages\\base_page.py\", line 112, in open_url\n    self.wait_for_page_load()\n  File \"C:\\Users\\Fr0z3n556\\Desktop\\automation_project\\pages\\base_page.py\", line 42, in wait_for_page_load\n    self.handle_alert(1)\n  File \"C:\\Users\\Fr0z3n556\\Desktop\\automation_project\\pages\\base_page.py\", line 27, in handle_alert\n    alert = WebDriverWait(self.driver, timeout).until(EC.alert_is_present())\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Fr0z3n556\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 129, in until\n    value = method(self._driver)\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Fr0z3n556\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 856, in _predicate\n    return driver.switch_to.alert\n           ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Fr0z3n556\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\selenium\\webdriver\\remote\\switch_to.py\", line 55, in alert\n    _ = alert.text\n        ^^^^^^^^^^\n  File \"C:\\Users\\Fr0z3n556\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\selenium\\webdriver\\common\\alert.py\", line 58, in text\n    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Fr0z3n556\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 458, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Fr0z3n556\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1758991111862, "stop": 1758991113335}], "start": 1758991111862, "stop": 1758991113344, "uuid": "ac2548b9-c396-41e5-89e9-ba9dc87c54cf", "historyId": "2650da391c980413bcdedeabba7a0a65", "testCaseId": "2650da391c980413bcdedeabba7a0a65", "fullName": "tests.test_form.TestForm#test_fill_and_submit_form", "labels": [{"name": "severity", "value": "critical"}, {"name": "story", "value": "Fill and submit form"}, {"name": "feature", "value": "Form Page"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_form"}, {"name": "subSuite", "value": "TestForm"}, {"name": "host", "value": "MakuOSPC"}, {"name": "thread", "value": "34040-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_form"}], "titlePath": ["tests", "test_form.py", "TestForm"]}